# Streamlit Community Cloud Configuration
# This file configures the deployment settings

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9ff"
textColor = "#262730"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[global]
developmentMode = false

[client]
showErrorDetails = true
toolbarMode = "minimal"