# Streamlit Secrets Configuration
# Add your API keys here for deployment (keep this file private)

# Example API keys - replace with actual values in Streamlit Cloud
# OPENAI_API_KEY = "your_openai_key_here"
# GEMINI_API_KEY = "your_gemini_key_here"
# SERPAPI_KEY = "your_serpapi_key_here"
# HUGGINGFACE_API_KEY = "your_hf_key_here"

# The app will work without these keys using fallback systems